name: govulncheck
on: [push]

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulnchecks
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.21.1
