name: Create Pre-Release and Assets
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*-rc*' # Push events to matching v*-rc*, i.e. v1.0.0-rc.1 (v 1.0.0 release candidate 1)

permissions:
    contents: write
    packages: write

jobs:
  read-changelog:
    name: Read CHANGELOG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Read CHANGELOG data
      # https://medium.com/@ibraheemabukaff/github-actions-exporting-multi-line-one-line-value-environment-variable-5bb86d01e866
        run: |
          changelog_text=$(cat "${{ github.workspace }}/CHANGELOG")
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo $changelog_text >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

  create-github-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ env.CHANGELOG }}
          draft: false
          prerelease: true

  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: "darwin/amd64","freebsd/amd64","freebsd/arm64","freebsd/arm","linux/amd64","linux/arm","linux/arm64","openbsd/amd64","openbsd/arm64","openbsd/arm","windows/amd64"
        goos: [linux, windows, darwin, freebsd, openbsd]
        goarch: [amd64, arm64, arm]
        exclude:
          - goarch: arm64
            goos: windows
          - goarch: arm
            goos: windows
          - goarch: arm64
            goos: darwin
          - goarch: arm
            goos: darwin
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goarm: 7
        goversion: "1.21.1"
        extra_files: LICENSE README.md plex_monitor.yaml
        compress_assets: auto