# .github/workflows/release.yaml

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: "darwin/amd64","freebsd/amd64","freebsd/arm64","freebsd/arm","linux/amd64","linux/arm","linux/arm64","openbsd/amd64","openbsd/arm64","openbsd/arm","windows/amd64"
        goos: [linux, windows, darwin, freebsd, openbsd]
        goarch: [amd64, arm64, arm]
        exclude:
          - goarch: arm64
            goos: windows
          - goarch: arm
            goos: windows
          - goarch: arm64
            goos: darwin
          - goarch: arm
            goos: darwin
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz"
        binary_name: "test-binary"
        extra_files: LICENSE README.md